travis:
  secure:
    BINSTAR_TOKEN: OImM3wYPPHN9otiEZO3kehbwZ8i7DDXIbdE59pmLbuMtXoXsenNYvjJ/Hb6gVJo4I9hUn4PnHdtG2IW1YGAv1VKrHba6kgzxK1dzSAbnZ7JtBHz9S/5clh7nTialNpB1kBEbh57VXXhg2xKFTp22kQUU7bhTJRwEqhhp/fXGDEvDLEpAqhDDXRSVrR7C9OZ/LFc4lFC7XYe7GVEpD5JJKroTYAePBpZC+nMavhkPJok4PCP8q2mSRX1jaivXDfIbakDOAk71EwJoBH/dJ7Ncv3Hykgc8/ZnVQeDMA0u5PB38RlwQHPd4fTC0ggyPT7tVgZ4EjkarLUL0y9RCLtjIpqpExgJaH7vWXnXeiId+QTzPZi1PhbEc1Ze0M2xTm7wnLpnJsU0FvaBCm2jwLB9V3wAoBXyc58zobYCTeRUJzotTnyU5aUa71ivEVQ/puR207/2ZxqnPc6eUSgX9tCgn6rfqsllpbWD+rCBCg9Byt6ojLGdLtf8TvxmW8wlPd+f/spEVmYBEXWZVG7sYsgTj/f+Jgqv6Qi3Eg8fgeo8BMjsO1FQRX5w/6zp72X9nVmogyKIVj67px8DE1F4IrgUyHLboOm4egQ64CkuflN5f8MMzwTz+ixpR1Gld0NhP3tYUFdpMvnyzgdOq9PJDO9/yXgdVCpI6v6U99ysLxpcwffs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
