travis:
  secure:
    BINSTAR_TOKEN: kxzwWTjm5fhbCwOxk2eO5PxEH4o9nVyqTa7OIcwW2AEi/V5nxKgFFX/BJguJJxvDwCHKwZX11XCxiQbN78nBcOE0T7epWl2WVKsxyv2ZROK/Xbih0gfCgjY8JxYKEaZv2aLEusHVRneDyFH73s2TPI5moTFQg5z77w5mcl/sXVOzlshoJ0BBKUgX+hbjC2CYpEhAkEs3cYHH1cOJ65BnM+g/XSBwbMjbjoxc0RnopqfuJn7nTqSzrhVX2M7YsJrnwHQ72Bkg7wt606J5vxXYTeqkwaYcEFrROEgIZIhaL1sggAEmMwdftaIhhcx7/OIyH0ka9+j3oxwFpR8sPGDE/4bsLi59Sp9hzwycKyFOqK6z/zX20vjKjB7TeqrKPwa2EZ2Tuu5EKOJvqQi5wU20WDwPCcxSKK7KvHId5yf1Iwks3TOPaePeeHwJBcgT8h28wVzbD5R16VTRbRHE7uGb3kuBrtlLiD7bcgpGldLSz/Dkk5bq3xWKuLhWmG+0ORv9Yjblf7uA+P82J89wxUYwMsR5OAoVsppDL8isP7hs6P1KK+x3SI1zvso1lURHZmGFrmLMrMGFkzWaQnAuULSVeRoBxs+tErpIOCycFe96+zTvFlFA2CREB79D/EsAjyHyEr8imRtFeP0QYPqazsZrYzkyh3EgO6QUn4VP2im+ths=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
