travis:
  secure:
    BINSTAR_TOKEN: Du6u5/VpwTKG9Z7Zi0E4aJZQI4xjfWWj0XJhrLsyb51pjppWty1kTo4Dodaze2sAQnWUmQwHIG+Xwa3yHTKb6yPImzkOsSka2+Vzw8ofFIh9QofJ1cmZnSZb2qcNOj1KcjdcN1lWY9WgwU5OZuxSC0n/+qdMt820p6Wx3dQvNev0Bog8zLGpdy8H2DDeD5p4fxh+mRasL/9cqO9Xpmjmbxm6xeQql9pgmETS53e1b9usGwDJq7/f/RzxxbtliJIUZrLCPv19HXlk7PB1qUpODUHFeacUcMFhG7JhVa/dbRW6GA42khO4fOc2/SpbxTalQn76QjP+0Jeonbrf96PNtjmQikpbdWvNQME7+uaBfS3pOACiRWnQjSVcqnp+aliQ8EhPPzwvZAF790orWIn4mWHXjWC/b1iTsurjxmMfisHiViLaXv+pefIE9Glm81VV1WMms+sufZp9wjXvce0eriN1ngvpdNNN+dUN10X9pd8r/dOCiKqD3ZQqlhz9cMFekoKTarceuO5N7pnzwS8b1L5RGIZap19GvXveCGLy0Otc1cqsZfn1dVc6SDiiJRjHlUsoYryRAKbIfJi/4daVQyQuqEmUC2qGewnpxg80Wgxro9M40Scjv5cM7mpyNFcnPQ6vMOMPQZRMZ6PwjOkl/xrXSaJ0bszm2xb5ErWoxc8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
